using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Relink_Mod_Manager
{
    public static class FASIcons
    {
        public static char Folder = '\uF07B'; // F07B, F114, 01F4C1, 01F5BF
        public static char FolderOpen = '\uF07C'; // F07C, F115, 01F4C2, 01F5C1
        public static char File = '\uF016'; // F016, F15B, 01F4C4, 01F5CB
        public static char HardDrive = '\uF0A0'; // F0A0, 01F5B4
        public static char Desktop = '\uF108'; // F108, F390, 01F5A5
        public static char Documents = '\uF0F6'; // F0F6, F15C, 01F5B9, 01F5CE
        public static char SquarePlus = '\uF0FE'; // F0FE, F196
        public static char Plus = '\u002B'; // 002B, 2795
        public static char FileMedical = '\uF477'; // F477
        public static char Minus = '\u2013'; // 2013, 2212, 2796, F068
        public static char SquareMinus = '\uF146'; // F146, F147
        public static char TrashCan = '\uF014'; // F014, F2ED
        public static char FileLines = '\uF0F6'; // F0F6, F15C, 01F5B9, 01F5CE
        public static char ChevronLeft = '\u2329'; // 2329, F053
        public static char ChevronRight = '\u232A'; // 232A, F054
        public static char ChevronUp = '\uF077'; // F077
        public static char ChevronDown = '\uF078'; // F078
        public static char Copy = '\uF0C5'; // F0C5
        public static char Upload = '\uF093'; // F093
        public static char FloppyDisk = '\uF0C7'; // F0C7, 01F4BE, 01F5AA
        public static char Sitemap = '\uF0E8'; // F0E8
        public static char ArrowRotateLeft = '\u21BA'; // 21BA, F0E2
        public static char FilePDF = '\uF1C1'; // F1C1
        public static char FileWord = '\uF1C2'; // F1C2
        public static char FileExcel = '\uF1C3'; // F1C3
        public static char FilePowerpoint = '\uF1C4'; // F1C4
        public static char FileImage = '\uF1C5'; // F1C5, 01F5BB
        public static char FileZipper = '\uF1C6'; // F1C6
        public static char FileAudio = '\uF1C7'; // F1C7
        public static char FileVideo = '\uF1C8'; // F1C8
        public static char FileCode = '\uF1C9'; // F1C9
        public static char Sliders = '\uF1DE'; // F1DE
        public static char ClockRotateLeft = '\uF1DA'; // F1DA
        public static char Server = '\uF233'; // F233
        public static char Clone = '\uF24D'; // F24D
        public static char WindowMaximize = '\uF2D0'; // F2D0, 01F5D6
        public static char WindowMinimize = '\uF2D1'; // F2D1, 01F5D5
        public static char WindowRestore = '\uF2D2'; // F2D2
        public static char RotateLeft = '\uF2EA'; // F2EA
        public static char Rotate = '\uF2F1'; // F2F1, 01F504
        public static char Pencil = '\u270F'; // 270F, F040, F303
        public static char Pen = '\uF304'; // F304, 01F58A
        public static char Clipboard = '\uF328'; // F328, 01F4CB
        public static char UpRightFromSquare = '\uF35D'; // F35D
        public static char RightLeft = '\uF362'; // F362
        public static char Box = '\uF466'; // F466, 01F4E6
        public static char BoxesStacked = '\uF468'; // F468, F4A1
        public static char ClipboardCheck = '\uF46C'; // F46C
        public static char ClipboardList = '\uF46D'; // F46D
        public static char IdCardClip = '\uF47F'; // F47F
        public static char NotesMedical = '\uF481'; // F481
        public static char BoxOpen = '\uF49E'; // F49E
        public static char UserLarge = '\uF406'; // F406
        public static char UserLargeSlash = '\uF4FA'; // F4FA
        public static char UserCheck = '\uF4FC'; // F4FC
        public static char UserClock = '\uF4FD'; // F4FD
        public static char UserGear = '\uF4FE'; // F4FE
        public static char UserPen = '\uF4FF'; // F4FF
        public static char UserGroup = '\uF500'; // F500, 01F465
        public static char UserLock = '\uF502'; // F502
        public static char UserMinus = '\uF503'; // F503
        public static char UserShield = '\uF505'; // F505
        public static char UserSlash = '\uF506'; // F506
        public static char UserTag = '\uF507'; // F507
        public static char UsersGear = '\uF509'; // F509
        public static char FileArrowDown = '\uF56D'; // F56D
        public static char FileExport = '\uF56E'; // F56E
        public static char FileImport = '\uF56F'; // F56F
        public static char FileInvoice = '\uF570'; // F570
        public static char FileArrowUp = '\uF574'; // F574
        public static char LayerGroup = '\uF5FD'; // F5FD
        public static char LocationCrosshairs = '\uF601'; // F601
        public static char FolderMinus = '\uF65D'; // F65D
        public static char FolderPlus = '\uF65E'; // F65E
        public static char FileCSV = '\uF6DD'; // F6DD
        public static char NetworkWired = '\uF6FF'; // F6FF
        public static char CheckToSlot = '\uF772'; // F772
        public static char Minimize = '\uF78C'; // F78C
        public static char GripLines = '\uF7A4'; // F7A4
        public static char GripLinesVertical = '\uF7A5'; // F7A5
        public static char BorderAll = '\uF84C'; // F84C
        public static char BorderNone = '\uF850'; // F850
        public static char BorderTopLeft = '\uF853'; // F853
        public static char TextSlash = '\uF87D'; // F87D
        public static char ArrowDownZA = '\uF881'; // F881
        public static char ArrowUpZA = '\uF882'; // F882
        public static char ArrowDownShortWide = '\uF884'; // F884
        public static char ArrowUpShortWide = '\uF885'; // F885
        public static char ArrowDown91 = '\uF886'; // F886
        public static char ArrowUp91 = '\uF887'; // F887
        public static char SpellCheck = '\uF891'; // F891
        public static char EarthEuropa = '\uF7A2'; // F7A2
        public static char Shapes = '\uF61F'; // F61F
        public static char StarOfLife = '\uF621'; // F621
        public static char CropSimple = '\uF565'; // F565
        public static char CheckDouble = '\uF560'; // F560
        public static char DeleteLeft = '\u232B'; // 232B, F55A
        public static char BarsStaggered = '\uF550'; // F550
        public static char NotEqual = '\uF53E'; // F53E
        public static char GreaterThanEqual = '\uF532'; // F532
        public static char LessThanEqual = '\uF537'; // F537
        public static char Infinity = '\u221E'; // 221E, 267E, F534
        public static char Divide = '\u00F7'; // 00F7, 2797, F529
        public static char ShieldBlank = '\uF3ED'; // F3ED
        public static char Microchip = '\uF2DB'; // F2DB
        public static char Snowbreak = '\u2744'; // 2744, 2746, F2DC
        public static char Stopwatch = '\u23F1'; // 23F1, F2F2
        public static char RightFromBracket = '\uF2F5'; // F2F5
        public static char RightToBracket = '\uF2F6'; // F2F6
        public static char DownLong = '\uF309'; // F309
        public static char LeftLong = '\uF30A'; // F30A
        public static char RightLong = '\uF30B'; // F30B
        public static char UpLong = '\uF30C'; // F30C
        public static char Maximize = '\uF31E'; // F31E
        public static char LeftRight = '\u2194'; // 2194, F337
        public static char UpDown = '\u2195'; // 2195, 2B0D, F338
        public static char DownLeftAndUpRightToCenter = '\uF422'; // F422
        public static char UpRightAndDownLeftFromCenter = '\uF424'; // F424
        public static char UserPlus = '\uF234'; // F234
        public static char UserXmark = '\uF235'; // F235
        public static char ShareNodes = '\uF1E0'; // F1E0
        public static char Wifi = '\uF1EB'; // F1EB
        public static char LifeRing = '\uF1CD'; // F1CD
        public static char CircleNotch = '\uF1CE'; // F1CE
        public static char Database = '\uF1C0'; // F1C0
        public static char Recycle = '\u2672'; // 2672, 267A, 267B, F1B8
        public static char Cubes = '\uF1B3'; // F1B3
        public static char Cube = '\uF1B2'; // F1B2
        public static char Ellipsis = '\uF141'; // F141
        public static char EllipsisVertical = '\uF142'; // F142
        public static char TurnDown = '\u2935'; // 2935, F3BE
        public static char TurnUp = '\u2934'; // 2934, F3BF
        public static char Wrench = '\uF0AD'; // F0AD, 01F527
    }
}
